// src/App.vue
<template>
  <div class="region top bar">
    <div class="region top left">
      <div class="container">
        <clock />
      </div>
    </div>
    <div class="region top right">
      <div class="container">
        <weather v-if="$store.state.config.loaded" />
      </div>
    </div>
  </div>
  <div class="region upper third">
    <div class="container">
      <weather-forecast v-if="$store.state.config.loaded" />
    </div>
  </div>
  <div class="region lower third">
    <div class="container">
      <calendar v-if="$store.state.config.loaded" />
    </div>
  </div>
</template>

<script>
import Calendar from "./components/Calendar.vue";
import Clock from "./components/Clock.vue";
import Weather from "./components/Weather.vue";
import WeatherForecast from "./components/WeatherForecast.vue";

export default {
  name: "App",
  components: {
    Calendar,
    Clock,
    Weather,
    WeatherForecast,
  },
  created() {
    this.$store.dispatch("loadConfig");
  },
};
</script>

<style>
body {
  zoom: 220%;
}
</style>

// src/App.svelte
<script>
  import Calendar from './lib/components/Calendar.svelte';
  import Clock from './lib/components/Clock.svelte';
  import Weather from './lib/components/Weather.svelte';
  import WeatherForecast from './lib/components/WeatherForecast.svelte';
  import { store } from './lib/store';
</script>

{#if $store.config.loaded}
  <div class="region top bar">
    <div class="region top left">
      <div class="container">
        <Clock />
      </div>
    </div>
    <div class="region top right">
      <div class="container">
        <Weather />
      </div>
    </div>
  </div>
  <div class="region upper third">
    <div class="container">
      <WeatherForecast />
    </div>
  </div>
  <div class="region lower third">
    <div class="container">
      <Calendar />
    </div>
  </div>
{/if}

<style>
  :global(body) {
    zoom: 220%;
  }
</style>
