// src/components/Clock.vue
<template>
  <div>
    <div class="normal medium">{{ date }}</div>
    <div class="bright large light">
      {{ hours }}:{{ minutes }}
      <sup class="dimmed">{{ seconds }}</sup>
    </div>
  </div>
</template>

<script>
import moment from "moment/min/moment-with-locales";

export default {
  name: "Clock",
  data() {
    return {
      date: "",
      hours: "",
      minutes: "",
      seconds: "",
    };
  },
  created() {
    let self = this;
    setInterval(function () {
      let now = moment().locale(self.$store.state.config.common.language);
      self.date = now.format("dddd, l");
      self.hours = timeNumber(now.hours());
      self.minutes = timeNumber(now.minutes());
      self.seconds = timeNumber(now.seconds());

      function timeNumber(number) {
        return number < 10 ? "0" + number : number;
      }
    }, 1000);
  },
};
</script>

// src/lib/components/Clock.svelte
<script>
  import moment from 'moment/min/moment-with-locales';
  import { onMount } from 'svelte';
  import { store } from '../store';

  let clock = $state({
    date: '',
    hours: '',
    minutes: '',
    seconds: '',
  });

  const language = $store.config.common.language;

  function timeNumber(number) {
    return number < 10 ? '0' + number : number;
  }

  function updateClock() {
    let now = moment().locale(language);
    clock.date = now.format('dddd, l');
    clock.hours = timeNumber(now.hours());
    clock.minutes = timeNumber(now.minutes());
    clock.seconds = timeNumber(now.seconds());
  }

  onMount(() => {
    updateClock();

    const interval = setInterval(updateClock, 1000);

    return () => clearInterval(interval);
  });
</script>

<div class="normal medium">{clock.date}</div>
<div class="bright large light">
  {clock.hours}:{clock.minutes}
  <sup class="dimmed">{clock.seconds}</sup>
</div>
